name: Continuous Training and Deployment

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight
  workflow_dispatch: # Run manually
  push:
    branches:
      - main

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Git user identity
      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Git pull on the server
      - name: Git pull on server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            # Navigate to the application directory and pull latest changes
            cd docker/experiments/insight-sync-application
            git pull origin main

      # Step 4: Execute commands directly inside the container on the server
      - name: Execute commands in container
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            # Run the training process inside the container
            docker exec flask_app_1 bash -c "
              python -m pip install --upgrade pip && \
              pip install dvc[all] && \
              pip install -r /app/requirements.txt && \
              echo '${{ secrets.GDRIVE_SERVICE_ACCOUNT_BASE64 }}' | base64 --decode > /app/google_services.json && \
              dvc remote modify storage gdrive_use_service_account true && \
              dvc remote modify storage gdrive_service_account_json_file_path /app/google_services.json && \
              dvc pull && \
              python /app/src/data_ingestion/youtube_comments/main.py && \
              python /app/src/scripts/main.py && \
              python /app/src/models/train_model.py && \
              git config --global user.name 'GitHub Actions' && \
              git config --global user.email 'actions@github.com' && \
              dvc add /app/data/train.csv && \
              git add /app/data/train.csv.dvc && \
              git commit -m 'Update dataset' && \
              dvc push
            "

            # Rebuild and redeploy the application container
            cd docker/experiments/insight-sync-application
            docker compose up -d --build
