name: Continuous Training and Deployment

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight
  workflow_dispatch: # Run manually
  push:
    branches:
      - main

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Git user identity
      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dvc[all]
          pip install -r requirements.txt

      # Step 5: Configure Google Drive credentials
      - name: Configure Google Drive credentials
        env:
          GDRIVE_SERVICE_ACCOUNT_BASE64: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_BASE64 }}
        run: |
          echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > google_services.json

      # Step 6: Configure DVC Remote for Google Drive
      - name: Configure DVC Remote
        run: |
          dvc remote modify storage gdrive_use_service_account true
          dvc remote modify --local storage gdrive_service_account_json_file_path google_services.json

      # Step 7: Pull dataset from DVC remote
      - name: Pull dataset
        run: dvc pull

      # Step 8: Run local preprocessing (Optional)
      - name: Run local preprocessing
        run: |
          python src/data_ingestion/youtube_comments/main.py
          python src/scripts/main.py
          dvc add data/train.csv
          git add data/train.csv.dvc
          git commit -m "Update dataset"
          dvc push

      # Step 9: Deploy to server
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            # Navigate to the application directory on the server
            cd docker/experiments/insight-sync-application

            # Pull the latest changes
            git pull origin main

            # Rebuild and redeploy Application services
            docker compose up -d --build

            # Run training commands inside the app container
            docker exec flask_app_1 bash -c "
              cd /app &&
              dvc pull &&
              python src/data_ingestion/youtube_comments/main.py &&
              python src/scripts/main.py &&
              python src/models/train_model.py &&
              dvc add data/train.csv &&
              git add data/train.csv.dvc &&
              git commit -m 'Update dataset' &&
              dvc push
            "
